# Generated by Django 3.0.7 on 2020-06-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0003_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer_text',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
    ]
