# Generated by Django 3.0.7 on 2020-06-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0004_useranswer_answer_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer_text',
            new_name='answered_text',
        ),
    ]
